### ISSUE TITLE
Excuse me, I wonder whether this coalign code can support the rgb v2x-sim?

### ISSUE THREAD

**Issue by WangzcBruce** [yifanlu0227/CoAlign#10]
If not, https://github.com/MediaBrain-SJTU/CoCa3D is another solution, is that right?

**Comment by yifanlu0227** [comment]
That's right. But the camera api for V2X-Sim has not been implemented yet, both in this repo and CoCa3D.

We use [Lift-Splat-Shoot](https://github.com/nv-tlabs/lift-splat-shoot) to realize the camera-based detection, and designed the data interface in intermediate_fusion_dataset.py and late_fusion_dataset.py. 

You only need to retrieve the camera data in the proper format in basedataset. I have implement this for OPV2V and DAIR-V2X-C dataset, also in this repo. If you want to use camera data in V2X-Sim, you can imitate those code to achieve it.

I will update camera-based detection code in this repo very soon. Today.

**Comment by yifanlu0227** [comment]
Code has been released. 

I understand that V2XSim dataset maybe important for you. However, due to my current workload, I'm unable to take on this task at the moment. I'm here to provide any guidance or support you may need during the process. Thank you for your understanding.

**Comment by WangzcBruce** [comment]
Thanks a lot, it will be helpful for me !!!
