### ISSUE TITLE
camera collaboration on the V2XSet dataset

### ISSUE THREAD

**Issue by Cyunon** [yifanlu0227/CoAlign#14]
Have you tested camera collaboration on the V2XSet dataset? It seems that this dataset has no additional data, such as bev_visibility.png

**Comment by yifanlu0227** [comment]
You are right. The label is for LiDAR, which is not suitable for camera-based detection. 

One alternative is to use this label but limit the detection range, like [-48m, -48m, +48m, +48m].

**Comment by Cyunon** [comment]
OK， thanks for your great work！
