### ISSUE TITLE
May I ask if you have parameter files for some models that have already been trained on v2xsim2.0

### ISSUE THREAD

**Issue by IndigoChildren** [yifanlu0227/CoAlign#15]
May I ask if you have parameter files for some models that have already been trained on this dataset, as I cannot train these models well on this dataset, and the metrics are a bit strange

**Comment by yifanlu0227** [comment]
Of course, I'd be happy to help.

[early fusion](https://drive.google.com/drive/folders/1FQgL90N8G6UrrsZ-wRbFDDZatUBA7rJq?usp=sharing)
[self-att](https://drive.google.com/drive/folders/1sIy9oYPqNPXrimIjQiyFpcjgpnMkj1SD?usp=sharing)
[v2x-vit](https://drive.google.com/drive/folders/1ojEkbSKO7xXOSgj4EfFK6lL6ZQIl0LgM?usp=sharing)
[coalign](https://drive.google.com/drive/folders/1LXoavMcaPWNGWNRZzcLaiWWARbS0RU1m?usp=drive_link)

**Comment by IndigoChildren** [comment]
thank you sooooo much!!
