### ISSUE TITLE
Questions about loss function

### ISSUE THREAD

**Issue by HuangZhe885** [yifanlu0227/CoAlign#19]
Thank you for your excellent work. I'm particularly interested in the derivation of the loss function using KL divergence in your research. I attempted to derive it myself, but due to my limited expertise, I wasn't able to reproduce the formulas presented in your paper. I would greatly appreciate it if you could kindly explain the derivation process.

Thank you again!

**Comment by yifanlu0227** [comment]
Hi, There is a great paper that details the KL divergence loss functions: [Uncertainty-Aware Voxel based 3D Object Detection and Tracking with von-Mises Loss](http://arxiv.org/abs/2011.02553). 

You can find a lot of useful derivations in it :)
