### ISSUE TITLE
The train/test pickle files in V2XSim 2.0

### ISSUE THREAD

**Issue by HuangZhe885** [yifanlu0227/CoAlign#24]
Thanks for your project.
 
I notice that  the code generating pkl file for V2X-Sim 2.0 is missing.

I use the file from https://github.com/yifanlu0227/CoAlign/issues/2#issuecomment-1455459287  without success:
`AssertionError: Error: there are 47638 label files but 47300 lidarseg records.`

The split file I used is associated with the  [coperception](https://github.com/coperception/coperception) project.  I was able to successfully build training and test sets for this project.

The Structure of V2XSim2.0  is :

                |-- v2.0
                |-- sweeps
                |-- maps
                |-- lidarseg
                |-- imu
                |-- gnss
Could you please provide the train/test pickle files in V2XSim2.0?

Thank you!

**Comment by yifanlu0227** [comment]
Of course!

https://drive.google.com/drive/folders/16_KkyjV9gVFxvj2YDCzQm1s9bVTwI0Fw?usp=sharing

**Comment by HuangZhe885** [comment]
> Of course!
> 
> https://drive.google.com/drive/folders/16_KkyjV9gVFxvj2YDCzQm1s9bVTwI0Fw?usp=sharing

Thanks again！
