### ISSUE TITLE
Question about the yamls of where2comm and when2com? 

### ISSUE THREAD

**Issue by WangzcBruce** [yifanlu0227/CoAlign#26]
![image](https://github.com/yifanlu0227/CoAlign/assets/45158420/bd5e6178-6157-4c4c-bc34-45298e77a94a)
Dear Lu! I'm sorry to bother you again! Excuse me, is there any available yaml about where2comm and when2com for opv2v?

**Comment by yifanlu0227** [comment]
These two fusion methods are incomplete in this Repo. And the performance and reproducibility can not be guaranteed. 

I would suggest you refer to their official Repos or migrate their implementation to CoAlign's framework :)
