### ISSUE TITLE
The Question regarding the results of a single detector

### ISSUE THREAD

**Issue by HuangZhe885** [yifanlu0227/CoAlign#28]
Hi, thank you for your work. I tried to use SECOND_uncertainty.yaml to train the single detector. The bounding box I generated was not very accurate. Could you please share the best checkpoints under these three datasets?  I want to check where exactly I went wrong.

**Comment by yifanlu0227** [comment]
Sorry, now only OPV2V's single detector w. uncertainty can be found in my disk. 

[Google Drive](https://drive.google.com/drive/folders/11gASqFORJ-Ut9G8k0EbiyPo1km9b2t9L?usp=drive_link)

The training of single detector w. uncertainty is not stable, which may get NaN sometimes. It is feasible to have multiple trails of training. And the loss may be higher than the w.o. uncertainty training.

**Comment by HuangZhe885** [comment]
By the way，I encountered some problems when installing d3d. It seemed that files were missing, cmake did not succeed.

<img width="749" alt="image" src="https://github.com/yifanlu0227/CoAlign/assets/44192081/e10315a7-cb65-4582-93bc-b4abbf80521f">

In cmakefile of d3d , 
https://github.com/yifanlu0227/d3d/blob/d741c03c4da1c3695ae7a096212a80af807ea448/d3d/CMakeLists.txt#L11C27-L11C27
 `add_subdirectory(math)`
Should 'math' be written as 'mathh' ?
