### ISSUE TITLE
 Do voxel_size_x and  voxel_size_y need to be the same？

### ISSUE THREAD

**Issue by wangsh2001** [yifanlu0227/CoAlign#29]
Hi~When using visual intermediate fusion methods，do voxel_size_x and  voxel_size_y need to be the same？

**Comment by yifanlu0227** [comment]
Not necessary. But you need to make it consistent with `grid_conf`. 

The last item in `xbound` / `ybound` needs to match the voxel_size_x and voxel_size_y to generate correct training labels.

**Comment by wangsh2001** [comment]
Okay, thank you
