### ISSUE TITLE
Experimental results on V2VNet and FPVRCNN

### ISSUE THREAD

**Issue by SyKszzzzz** [yifanlu0227/CoAlign#3]
Hi, I have run the code of FPVRCNN and V2VNet and V2VNet_robust on DAIR V2X, OPV2V respectively according to the provided code, but there is always a situation that the result cannot be obtained during inference.

**Comment by yifanlu0227** [comment]
Hi, you can access the google drive to get my experiment logs. 

https://drive.google.com/drive/folders/1uZLDOZFHUtr8VpQ9XOSvAXZr2xVvdGC1?usp=sharing

From my experience, V2VNet is very difficult to train. We encounter the situation that even after training 60 the epoch, the loss remains unconverged (> 1). I think this has something to do with the initialization of the model, and the one-round-communication setting which warps feature map increases the difficulty of learning. I trained several V2VNet at the same time, one of which was convergent, which I showed in the paper.

For FPVRCNN and V2VNet_robust, please carefully follows the [readme](https://github.com/yifanlu0227/CoAlign/tree/main/opencood/hypes_yaml#readme). The latter has no official open-source dataset and code, so I can't fully verify the effect of the reproduction on the new dataset. 

I hope this help.
