### ISSUE TITLE
About the Agent-Object Pose Graph

### ISSUE THREAD

**Issue by uestchjw** [yifanlu0227/CoAlign#30]
Hi, thanks for your valuable work.

In my understanding, the premise for using the agent-object pose graph is that the same object can always be seen between two perspectives, but this premise may not always be satisfied, especially in DAIR-V2X datasets. I'm curious about how this problem was solved.

Thank you for any response.

**Comment by yifanlu0227** [comment]
You are correct, agents must observe the same object to perform the agent-object pose graph optimization. If two agents are too far apart, as you mentioned, they can not build the graph and correct their relative poses. 

So it is indeed a premise. But I'd like to explain in two ways:

1. If there is no relationship (like common observation) between the two agents, it is nearly impossible for them to correct their poses. This case does exist in the dataset, and the optimization will do nothing but return their original poses.
2. The collaboration occurs within a specific communication range (`comm_range` in the yaml config). With this prerequisite, they usually have common detected objects.
